apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: testagain 
  janus-idp.io/tekton: testagain
  backstage.io/kubernetes-id: testagain
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: testagain
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  