apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: testagain
  janus-idp.io/tekton: testagain
  backstage.io/kubernetes-id: testagain
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: testagain
resources:
- deployment.yaml
- route.yaml
- service.yaml
